name: GitHub Actions Vercel Production Deployment
env:
  VERCEL_ORG_ID: Q8esKtg3ENB1XkeFyRo5lqJs
  VERCEL_PROJECT_ID: prj_OEehib0BFOXLkBgB2DV3anYzFnyO
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=DIj85LauZRme4719HVZRZZTn
      - name: Build Project Artifacts
        run: vercel build --prod --token=DIj85LauZRme4719HVZRZZTn
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=DIj85LauZRme4719HVZRZZTn
      