name: Run Tests

on:
  push:
    branches:
      - main
      - deployment-back

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: tests # Specify the path to the root directory


      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          path: tests # Specify the path to the root directory

      - name: Install dependencies
        run: npm ci
        working-directory: tests # Specify the path to the root directory

      - name: Run tests
        run: npm test
        working-directory: tests # Specify the path to the root directory